[deps]
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CUDAapi = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NeuralVerification = "146f25fa-00e7-11e9-3ae5-fdbac6e12fa7"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
PDFIO = "4d0d745f-9d9a-592e-8d18-1ad8a0f42b92"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
QHull = "a8468747-bd6f-53ef-9e5c-744dbc5c59e7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatPlots = "60ddc479-9b66-56df-82fc-76a74619b69c"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
